version: "3"

services:
  app:
    container_name: containerize_app_1
    build:
      context: "./app"
    environment:
      FLASK_ENV: development
    ports:
      - ${APP_PORT:-5000}:${FLASK_RUN_PORT:-5000}
    volumes:
      - ./app/src:/home/app/src:rw
    links:
      - db
    depends_on:
      - db

  db:
    container_name: containerize_db_1
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 2s
      retries: 3
    restart: on-failure:3